language: objective-c
os: osx
osx_image: xcode7.3
xcode_sdk: macosx10.11
sudo: required
branches:
  only:
    - master
install:
  - sudo xcodebuild -project BGMApp/BGMAppTests/NullAudio/AudioDriverExamples.xcodeproj -target NullAudio DSTROOT="/" install
  - sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod || sudo killall coreaudiod
script:
  - yes | ./build_and_install.sh
  - cat build_and_install.log
  - find */build/Release/*/ -type f -exec md5 {} \;
  - system_profiler SPAudioDataType
  - say -a '?'
  - osascript -e 'tell application "Background Music" to quit'
  - xcodebuild -workspace BGM.xcworkspace -scheme 'Background Music Device' test
  - xcodebuild -workspace BGM.xcworkspace -scheme 'Background Music' test
  - xcodebuild -workspace BGM.xcworkspace -scheme 'BGMXPCHelper' test
  - yes | ./uninstall.sh
  - ls /Applications /Library/Audio/Plug-Ins/HAL /usr/local/libexec /Library/Application\ Support/Background\ Music
